
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ vm_hostname }}"

- name: Update /etc/hosts with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.1.1       {{ vm_hostname }}"
    insertafter: '^127\.0\.0\.1'
    state: present

